name: ci
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - run: yarn
      - run: yarn check