name: Node.js Package
on:
  release:
    types: [edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@wundergraph'
#      - run: yarn
      - run: set-version
      - run: cat package.json
#      - run: yarn publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}